architect:
  - yegor256
  - davvd
docker:
  image: yegor256/rultor-image:1.20.0
assets:
  rubygems.yml: zerocracy/home#assets/rubygems.yml
install: |-
  sudo bundle install --no-color "--gemfile=$(pwd)/Gemfile"
merge:
  script: |-
    bundle exec jekyll build
