# The MIT License (MIT)
#
# Copyright (c) 2018-2025 Zerocracy
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
---
title: Blog@Zold
email: blog@zold.io
description: >
  Blog about Zold and other cryptocurrencies
baseurl: ""
url: "https://blog.zold.io"
twitter_username: 0crat
markdown: kramdown
author:
  name: "Yegor Bugayenko"
  email: yegor256@gmail.com
encoding: utf-8
timezone: Europe/Moscow
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

permalink: :year/:month/:day/:title.html
paginate: 8
paginate_path: "p/:num"
excerpt_separator: <!--more-->

feed:
  title: Blog@Zold
  subtitle: Blog about Zold and other cryptocurrencies
  path: rss.xml

sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: false
