source 'https://rubygems.org'

gem 'jekyll', '~>3.2'
gem 'jekyll-feed', '~>0.5'
gem 'jekyll-paginate', '~>1.1'
gem 'jekyll-sitemap', '~>0.10'
gem 'jekyll-bits'
gem 'rake', '~>10.4'
gem 'scss_lint', '~>0.38'
gem 'w3c_validators', '~>1.1'
gem 'html-proofer', '~>3.0'
gem 'rubocop', '~>0.24'
gem 'rubocop-rspec', '~>1.2'
gem 'jgd', '~>1.6'
